export { default as image01 } from './image_01.png';
export { default as image02 } from './image_02.png';
export { default as image01Zoomed } from './image_01_zoomed.png';
export { default as slider01 } from './slider_01.png';
export { default as slider02 } from './slider_02.png';
export { default as slider03 } from './slider_03.png';
export { default as slider04 } from './slider_04.png';
export { default as slider05 } from './slider_05.png';
export { default as carIcon } from './car_icon.png';
